### ISSUE TITLE
[META] APIs for Extension Point for creating a detector of AD

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#100]
### Is your feature request related to a problem?
The current architecture of plugins requires extension points for AD plugin to interact with OpenSearch from receiving a request from user to create a detector to returning the response to the user. The extension points which needs to be extensible are:

- [x] getRestHandlers https://github.com/opensearch-project/opensearch-sdk/issues/64
- [x] createComponents https://github.com/opensearch-project/opensearch-sdk/issues/78
- [x] getSettings https://github.com/opensearch-project/opensearch-sdk/issues/79
- [x] getActions https://github.com/opensearch-project/opensearch-sdk/issues/80

### What solution would you like?
_A clear and concise description of what you want to happen._

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._
