### ISSUE TITLE
Meta: [FEATURE/Extensions] Interaction of AD Extension with OpenSearch

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#132]
### Is your feature request related to a problem?
After integrating SDK with AD Extension in #24, the next steps would be for AD Extension to interact with OpenSearch for creating a detector. Below are the steps of the workflow:
1. Initialize the extension and initialize the interfaces of the extension points.
2. Registered the REST APIs in OpenSearch
3. Send a Create Detector request to extension which will be redirected to the handler from `handleRequest`. If it fails exception will thrown on AD Extension and to throw the same exception on OpenSearch `listener.onFailure` will be invoked.
4. The handler will take care of calling Create Index API to create AD index on OpenSearch using the SDKClient.

![sequence](https://user-images.githubusercontent.com/16099877/189458766-029142d6-ff4e-4128-92c2-6d9af7195f07.png)

There will be bugs/issues after integrating all the SDK features with AD Extension and making it to interact with OpenSearch. We will turn this into a meta issue then and split the work to fix those.

Steps/ Sub issues:

- [x]  [getSettings](https://github.com/opensearch-project/opensearch-sdk-java/issues/159) - Register custom AD Extension settings in OpenSearch https://github.com/opensearch-project/anomaly-detection/pull/686

- [x] [getRestHandler](https://github.com/opensearch-project/opensearch-sdk-java/issues/58) - Register POST route for create detector in OpenSearch
- [x] [createComponent](https://github.com/opensearch-project/opensearch-sdk-java/issues/160) Initialize `searchFeatureDao`, `anomalyDetectionIndices`, `adTaskManager` objects using the Transport APIs created [here](https://github.com/opensearch-project/opensearch-sdk-java/issues/78). - not needed for creating a detector but will be needed for next set of features
- [x] [getActions](https://github.com/opensearch-project/opensearch-sdk-java/issues/161) - Register custom AD actions in OpenSearch - Since AD create detector is working on one extension node. Keeping this on hold as extension to extension communication will be needed for the AD feature which requires details from all the AD extension nodes.
- [x] [Finally](https://github.com/opensearch-project/opensearch-sdk-java/issues/58), send a request to create a detector to OpenSearch, should be redirected to AD Extension and later a request will be send back to OpenSearch to create the detector.
