### ISSUE TITLE
[META] Implement Validate Detector for AnomalyDetector Extension

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#217]
### Is your feature request related to a problem?

Old plugin APIs for Validate Detector:

Validate the JSON format
```
POST _plugins/_anomaly_detection/detectors/_validate
POST _plugins/_anomaly_detection/detectors/_validate/detector
```

Validate the quality of the detector and get suggestions on improving
```
POST _plugins/_anomaly_detection/detectors/_validate/model
```

Components of this feature (Issues to be created and will be linked here):

For the detector validation:

 - [x] Create a new Rest Handler for the above routes - https://github.com/opensearch-project/opensearch-sdk-java/issues/221
 - [ ] Copy the detector validation logic from the existing plugin into the new handler - https://github.com/opensearch-project/opensearch-sdk-java/issues/222 
 - [ ] Process the response from the Rest Client into an appropriate ExtensionRestResponse - https://github.com/opensearch-project/opensearch-sdk-java/issues/224
 - [ ] Integrate the validation logic into the Create Detector (don't create a detector if it fails validation and provide useful error message) - https://github.com/opensearch-project/opensearch-sdk-java/issues/226

For the model validation:

 - [ ] Copy the model validation logic from the existing plugin into the new handler - https://github.com/opensearch-project/opensearch-sdk-java/issues/223
 - [ ] Process the response from the Rest Client into an appropriate ExtensionRestResponse - https://github.com/opensearch-project/opensearch-sdk-java/issues/225

**Comment by dbwiddis** [comment]
Superceded by #353
