### ISSUE TITLE
Add versioning support for SDK

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#337]
## Problem
We have seen problems across the project that plugins have compile time dependency on OpenSearch which is why they have to be released every version. 
https://github.com/opensearch-project/OpenSearch/issues/1707

## Why
We'd like to fundamentally solve this problem for extensions i.e SDK to work with multiple versions of OpenSearch.
To launch Extensions SDK we believe it adds value for developers supporting multiple versions of OpenSearch from day1. 

### Minor Version Compatibility Phase 1
- [x] [Design and build forward compatibility and backward compatibility for SDK](https://github.com/opensearch-project/opensearch-sdk-java/issues/338)
- [x] opensearch-project/opensearch-sdk-java#346
- [x] opensearch-project/OpenSearch#7402
- [ ] opensearch-project/opensearch-sdk-java#347

### Minor Version Compatibility Phase 1.5
- [ ] https://github.com/opensearch-project/OpenSearch/issues/2283

### Major Version Compatibility Phase 2
- [ ] Add backward and forward compatibility support for Major versions
- [ ] Evaluate compile time dependencies of SDK and abstract `opensearch.core` classes ([Decoupling](https://github.com/opensearch-project/OpenSearch/issues/5910))
