### ISSUE TITLE
Migrate Start Detector job to SDK using SDKRestClient

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#383]
### Is your feature request related to a problem?
 
Part of https://github.com/opensearch-project/OpenSearch/issues/5224
 
### What solution would you like?
 
Migrate the Start Detector job Rest API to Extensions SDK using SDKRestClient.
 
Use the implementation of #353 as a reference.  Add new issues for any steps you skip.
 
Implement the following API endpoints:
 - [x] `POST _plugins/_anomaly_detection/detectors/<detectorId>/_start`

**Comment by joshpalis** [comment]
### Remaining Tasks :
Replace the following instances in which `client.execute()` is used to trigger actions registered within OpenSearch with corresponding methods made available by the Java Client ([OpenSearchAsyncClient](https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/OpenSearchAsyncClient.java)).

- [ ] [AnomalyDetectionIndicies.updateJobIndexSettingIfNecessary()](https://github.com/joshpalis/anomaly-detection/blob/1e097c9d26aed1ab806f2643e1fe4465cc40fd88/src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java#L1086)
  - Action : GetSettingsAction
  - Request: GetSettingsRequest
  - Response : GetSettingsResponse
  - Note : Once this client.execute is replaced, uncomment `anomalyDetectionIndices.update()` in the following two places
     - [IndexAnomalyDetectorTransportAction](https://github.com/joshpalis/anomaly-detection/blob/1e097c9d26aed1ab806f2643e1fe4465cc40fd88/src/main/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportAction.java#L150)
     - [ADTaskManager](https://github.com/joshpalis/anomaly-detection/blob/1e097c9d26aed1ab806f2643e1fe4465cc40fd88/src/main/java/org/opensearch/ad/task/ADTaskManager.java#L300)
- [ ] [ADTaskManager.updateLatestFlagOfOldTasksAndCreateNewTask()](https://github.com/joshpalis/anomaly-detection/blob/1e097c9d26aed1ab806f2643e1fe4465cc40fd88/src/main/java/org/opensearch/ad/task/ADTaskManager.java#L1523)
  - Action : UpdateByQueryAction
  - Request: UpdateByQueryRequest
  - Response: BulkByScrollResponse
- [ ] ADTaskManager.deleteTaskDocs() 
  - Action : BulkAction
  - Request: BulkRequest
  - Response: BulkResponse

- [ ] ADTaskManager.cleanChildTasksAndADResultsOfDeletedTask()				
  - First Action: 
	  - Action : DeleteByQueryAction
	  - Request: DeleteByQueryRequest
	  - Response: BulkByScrollResponse
				
  - Second Action :
	- Action : DeleteByQueryAction
	- Request : DeleteByQueryRequest
	- Response : BulkByScrollResponse



### Current Blockers : (Will be handled as part of https://github.com/opensearch-project/opensearch-sdk-java/issues/525)

When Anomaly Detection Start Detector is invoked, Anomaly Detection sends a request to Job Scheduler to register job details (Job Index Name, Job Type Name, Action Name to parse ScheduledJobParameters, Action Name to run the extension job). Job Scheduler utilizes the Node client to execute the actions provided by the extension through the `ExtensionProxyAction`, which maintains a map of extension actions registered via `getActions()`. One such instance in which Job Scheduler is triggering these actions is [here](https://github.com/opensearch-project/job-scheduler/blob/4649c3d55f1485a3734ba86f4ff4024367e28192/src/main/java/org/opensearch/jobscheduler/utils/JobDetailsService.java#L173) to parse the `ScheduledJobParameter` indexed by AD. The action name provided with the request to trigger `ExtensionProxyAction` is then used to reroute the action request to the extension. 

Currently there is no handler within the SDK to handle transport action requests to extensions and thus the following error occurs. :
```
[2023-03-10T22:10:40,693][INFO ][o.o.j.u.JobDetailsService] [dev-dsk-jpalis-2c-27c8aa11.us-west-2.amazon.com] Sending ScheduledJobParameter parse request to extension : ad-extension-1
[2023-03-10T22:10:40,702][ERROR][o.o.j.u.JobDetailsService] [dev-dsk-jpalis-2c-27c8aa11.us-west-2.amazon.com] Could not parse job parameter
org.opensearch.transport.RemoteTransportException: [ad-extension][127.0.0.1:4532][internal:extensions/handle-transportaction]
Caused by: org.opensearch.transport.ActionNotFoundTransportException: No handler for action [internal:extensions/handle-transportaction]
        at org.opensearch.transport.InboundAggregator.lambda$new$0(InboundAggregator.java:75) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundAggregator.initializeRequestState(InboundAggregator.java:217) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundAggregator.headerReceived(InboundAggregator.java:94) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:167) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:94) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
```

**Comment by joshpalis** [comment]
### Tasks To Enable Historical Analysis

- [ ] Integrate `ForwardADTaskAction` with the SDK and register within `getActions`
- [ ] Modify `ADTaskManager.forwardRequestToLeadNode` to remove `hashring` and redirect the `ForwardADTaskRequest` to the extension node
- [ ] Remove `hashring` from `ADTaskManager.checkTaskSlots` and execute `ADStatsNodesAction` for extension node only
- [ ] Remove `hashring` from `ADTaskManager.startHistoricalAnalysis` and `forwardDetectRequestToCoordinationNode` for only the extension node. ADVersion should just be defaulted to current
- [X] Register `ad-batch-task-threadpool` as an executor builder. Already added in by https://github.com/opensearch-project/anomaly-detection/pull/876
- [ ] Integrate `ADBatchAnomalyResultAction` with the SDK and register within `getActions`. Called by `ADTaskManager.runNextEntityForHCADHistorical` (This just calls ADBatchTaskRunner.run for each request). Note : a potential issue may be in `ADBatchTaskRunner.getDateRangeOfSourceData()` as the aggregation response may be of a different type, will need to check during testing
- [ ] Modify `ADBatchTaskRunner.getTopEntitiesListener` and remove `hashring` to direct all high cardinality tasks back to the extension node
- [ ] Modify `ADBatchTaskRunner.forwardOrExecuteEntityTask` and ensure that ADBatch Task is executed locally on the extension node. (This negates the need to register `ADBatchTaskRemoteExecutionAction` as all tasks will be executed on the extension node)
- [ ] Potential issue : double check the response aggregation class within `SearchFeatureDao.getHighestCountEntities()` is of type `CompositeAggregation` after sending the search request with the `SDKRestClient`
- [ ] Potential Issue : double check `SearchFeatureDao.parseBucketAggregationResponse` as the aggregation class `InternalComposite` may not be supported by HLRC
- [ ] Potential issue : double check `AbstractRetirever.parseAggregation` as the aggregation class `InternalSingleBucketAggregation` may not be supported by HLRC
- [ ] Replace `StringTerms` with `ParsedStringTerms` in `ADBatchTaskRunner.searchTopEntitiesForSingleCategoryHC` as the `SDKRestClient` uses the `HLRC` internally
- [ ] Fix affected test classes

**Comment by minalsha** [comment]
@joshpalis  PR:https://github.com/opensearch-project/anomaly-detection/pull/837 is merged for start detector. Can we close this issue?
