### ISSUE TITLE
[META] Integrate the Job Scheduler Communication Mechanism with Anomaly Detection Extension to enable extensions to schedule jobs

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/opensearch-sdk-java#427]
## Problem
Upon completing the development of the communication mechanism between Job Scheduler as a plugin and Anomaly Detector as an extension, it is necessary to integrate these changes to the start detector workflow to enable job scheduling for anomaly detectors. The exploration and sequence diagram of the start detector workflow along with the work items for the communication mechanism can be viewed in this meta issue here : https://github.com/opensearch-project/OpenSearch/issues/5585.

## Anomaly Detection Features Dependent on Job Scheduler
The integration of the Job Scheduler Communication Mechanism is necessary to enable the following feature:

- https://github.com/opensearch-project/opensearch-sdk-java/issues/383

Additionally, the following features require job scheduling to be enabled in order to retrieve scheduled job details for a detector and to also stop a detector job execution

- https://github.com/opensearch-project/opensearch-sdk-java/issues/381
- https://github.com/opensearch-project/opensearch-sdk-java/issues/384
- https://github.com/opensearch-project/opensearch-sdk-java/issues/451

Work items for the integration will be created and linked here 

**Start Detector Tasks**
- [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/499 
- [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/304
- [x] #453
- [x] Integrate and trigger `AcquireLock` API prior to `StartDetector` execution
- [x] Integrate and trigger `ReleaseLock` API after `StartDetector` completion

**Stop Detector Tasks**
- [x] TBD

**Profile Detector Tasks**
- [x] TBD

## Job Scheduler Communication Mechanism Sequence Diagram
The following sequence diagram provides a detailed overview of the job registration process and job execution for extensions.
![JSCommunicationMechanism](https://user-images.githubusercontent.com/99766446/217953180-a01d37c8-0fe4-4316-b969-8e768dfc34fb.png)

**Comment by joshpalis** [comment]
Completed by https://github.com/opensearch-project/anomaly-detection/pull/880
