### ISSUE TITLE
[FEATURE] Migrate Get Detector using Job Scheduler to SDK using SDKRestClient

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#451]
### Is your feature request related to a problem?
 
Part of https://github.com/opensearch-project/OpenSearch/issues/5224
 
### What solution would you like?
 
Migrate the Get Detector Rest API to Extensions SDK using SDKRestClient.
 
Use the implementation of #353 as a reference.  Add new issues for any steps you skip.
 
Implement the following API endpoints:
 - [x] `GET _plugins/_anomaly_detection/detectors/<detectorId>?job=true`
 - [x] `GET _plugins/_anomaly_detection/detectors/<detectorId>?task=true`

**Comment by joshpalis** [comment]
**Tasks**

- [ ] Add routes/replacedRoutes to `RestGetAnomalyDetectorAction`
- [ ]

**Comment by joshpalis** [comment]
Note : Historical Detection does not have an associated job, therefore it is only necessary to check for historical batch tasks
## Get Detector for Historical Single Entity Detector (task=true)
## Get Detector for Historical Multi Entity Detector (task=true)

**Comment by joshpalis** [comment]
## Tasks to complete

- [ ] Test `job=true` for single entity real time detectors
- [ ] Test `job=true` for multi entity real time detectors
- [ ] Test `task=true` for single entity real time detectors
- [ ] Test `task=true` for multi entity real time detectors
- [ ] Test `task=true` for single entity historical detectors
- [ ] Test `task=true` for multi-entity historical detectors

## Tasks to enable retrieving task information for HCAD

- [ ] Modify `ADTaskManager.getADTaskProfile` and remove the hashring
- [ ] Integrate `ADTaskProfileAction` with the SDK and register within `getActions`
- [ ] Remove hashring from `ADTaskProfileTransportAction` node operation and set AD version to current
- [ ] fix affected test classes

**Comment by joshpalis** [comment]
All APIs have been tested successfully
